authors = [
    dict(
        id=0,
        first_name="W.D.",
        last_name="Ross",
    ),
    dict(
        id=1,
        first_name="D.P.",
        last_name="Chase",
    ),
    dict(
        id=2,
        first_name="J.A.K.",
        last_name="Thomson",
    ),
    dict(
        id=3,
        first_name="Robert",
        last_name="Bartlett",
    ),
    dict(
        id=4,
        first_name="Susan",
        last_name="Collins",
    ),
]


books = [
    dict(
        id=0,
        title="Nicomachean Ethics",
        first_publish_year="1908",
        authors=[0],
    ),
    dict(
        id=1,
        title="The Nicomachean Ethics of Aristotle",
        first_publish_year="1911",
        authors=[1],
    ),
    dict(
        id=2,
        title="The Nicomachean Ethics",
        first_publish_year="1953",
        authors=[2],
    ),
    dict(
        id=3,
        title="Aristotle's Nicomachean Ethics",
        first_publish_year="2011",
        authors=[3, 4],
    ),
]


quotes = [
    dict(
        id=0,
        description="Opening part, Book 1, Part 1",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=1,
        description="Reasonable expectations of precision, Book 1, Part 3",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=2,
        description="The young man, Book 1, Part 3",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=3,
        description="Jab at Plato, Book 2, Part 2",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=4,
        description="What is the highest of all goods?, Book 1, Part 4",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=5,
        description="Virtue definition, Book 2, Part 6",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=6,
        description="Emphasis on specific instances, Book 2, Part 7",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=7,
        description="Courage intro, Book 3, Part 6",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=8,
        description="Temperance intro, Book 3, Part 10",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=9,
        description="Liberality intro, Book 4, Part 1",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=10,
        description="Magnificence intro, Book 4, Part 2",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=11,
        description="Greatness of soul intro, Book 4, Part 3",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=12,
        description="Love of honor intro, Book 4, Part 4",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=13,
        description="Good-temperedness intro, Book 4, Part 5",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=14,
        description="Friendliness intro, Book 4, Part 6",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=15,
        description="?Truthfulness? intro, Book 4, Part 7",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=16,
        description="Wit intro, Book 4, Part 8",
        preferred_translation=None,
        original_greek=None,
    ),
    dict(
        id=17,
        description="Shame intro, Book 4, Part 8",
        preferred_translation=None,
        original_greek=None,
    ),
]


translations = (
    dict(
        id=0,
        text="Every art and every inquiry, and similarly every action and pursuit, is thought to aim at some good; and for this reason the good has rightly been declared to be that at which all things aim. But a certain difference is found among ends...",
        quote_id=0,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        id=1,
        text="""Every art, and every science reduced to a teachable form, and in like manner every action and moral choice, aims, it is thought, at some good: for which reason a common and by no means a bad description of the Chief Good is, "that which all things aim at." Now there plainly is a difference in the Ends proposed...""",
        quote_id=0,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        id=2,
        text="""Every art and every investigation, and similarly every action and pursuit, is considered to aim at some good. Hence the good has been rightly defined as 'that at which all things aim'. Clearly, however, there is some difference between the ends at which they aim...""",
        quote_id=0,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        id=3,
        text="""Every art and every inquiry, and similarly every action as well as choice, is held to aim at some good. Hence people have nobly declared that the good is that at which all things aim. But there appears to be a certain difference among the ends...""",
        quote_id=0,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        id=4,
        text="""We must be content, then, in speaking of such subjects and with such premisses to indicate the truth roughly and in outline, and in speaking about things which are only for the most part true and with premisses of the same kind to reach conclusions that are no better. In the same spirit, therefore, should each type of statement be received; for it is the mark of an educated man to look for precision in each class of things just so far as the nature of the subject admits; it is evidently equally foolish to accept probable reasoning from a mathematician and to demand from a rhetorician scientific proofs.""",
        quote_id=1,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        id=5,
        text="""We must be content then, in speaking of such things and from such data, to set forth the truth roughly and in outline; in other words, since we are speaking of general matter and from general data, to draw also conclusions merely general. And in the same spirit should each person receive what we say: for the man of education will seek exactness so far in each subject as the nature of the thing admits, it being plainly much the same absurdity to put up with a mathematician who tries to persuade instead of proving, and to demand strict demonstrative reasoning of a Rhetorician.""",
        quote_id=1,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        id=6,
        text="""Therefore in discussing subjects and arguing from evidence, conditioned in this way, we must be satisfied with a broad outline of the truth; that is, in arguing about what is for the most part so from premisses which are for the most part true we must be content to draw conclusions that are similarly qualified. The same procedure, then, should be observed in receiving our several types of statement; for it is a mark of the trained mind never to expect more precision in the treatment of any subject than the nature of that subject permits; for demanding logical demonstrations from a teacher of rhetoric is clearly about as reasonable as accepting mere plausibility from a mathematician.""",
        quote_id=1,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        id=7,
        text="""It would certainly be desirable enough, then, if one who speaks about and on the basis of such things demonstrate the truth roughly and in outline, and if, in speaking about and on the basis of things that are for the most part so, one draw conclusions of that sort as well. Indeed, in the same manner one must also accept each of the points being made. For it belongs to an educated person to seek out precision in each genus to the extent that the nature of the matter allows: to accept persuasive speech from a skilled mathematician appears comparable to demanding demonstrations from a skilled rhetorician.""",
        quote_id=1,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        id=8,
        text="""Hence a young man is not a proper hearer of lectures on political science; for he is inexperienced in the actions that occur in life, but its discussions start from these and are about these; and, further, since he tends to follow his passions, his study will be vain and unprofitable, because the end aimed at is not knowledge but action. And it makes no difference whether he is young in years or youthful in character; the defect does not depend on time, but on his living, and pursuing each successive object, as passion directs. For to such persons, as to the incontinent, knowledge brings no profit; but to those who desire and act in accordance with a rational principle knowledge about such matters will be of great benefit.""",
        quote_id=2,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        id=9,
        text="""Hence the young man is not a fit student of Moral Philosophy, for he has no experience in the actions of life, while all that is said presupposes and is concerned with these: and in the next place, since he is apt to follow the impulses of his passions, he will hear as though he heard not, and to no profit, the end in view being practice and not mere knowledge. And I draw no distinction between young in years, and youthful in temper and disposition: the defect to which I allude being no direct result of the time, but of living at the beck and call of passion, and following each object as it rises. For to them that are such the knowledge comes to be unprofitable, as to those of imperfect self-control: but, to those who form their desires and act in accordance with reason, to have knowledge on these points must be very profitable.""",
        quote_id=2,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        id=10,
        text="""That is why a young man is not a fit person to attend lectures on political science, because he is not versed in the practical business of life from which politics draws its premissses and subject-matter. Besides, he tends to follow his feelings, with the result that he will make no headway and derive no benefit from his course, since the object of it is not knowledge but action. It makes no difference whether he is young in age or youthful in character; the defect is due not to lack of years but to living, and purusing one's various aims, under sway of the feelings; for to people like this knowledge becomes as unprofitable as it is for the incontinent. On the other hand, for those who regulate their impulses and act in accordance with principle a knowledge of these subjects will be of great advantage.""",
        quote_id=2,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        id=11,
        text="""Hence of the political art, a young person is not an appropriate student, for he is inexperienced in the actions pertaining to life, and the arguments are based on these actions and concern them. Further, because he is disposed to follow the passions, he will listen pointlessly and unprofitably, since the end involved is not knowledge but action. And it makes no difference at all whether he is young in age or immature in character: the deficiency is not related to time but instead arises on account of living in accord with passion and pursuing each passion in turn. .For to people of that sort, just as to those lacking self-restraint, knowledge is without benefit. But to those who fashion their longings in accord with reason and act accordingly, knowing about these things would be of great profit.""",
        quote_id=2,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        id=12,
        text="""Since, then, the present inquiry does not aim at theoretical knowledge like the others (for we are inquiring not in order to know what virtue is, but in order to become good, since otherwise our inquiry would have been of no use), we must examine the nature of actions, namely how we ought to do them; for these determine also the nature of the states of character that are produced, as we have said.""",
        quote_id=3,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        id=13,
        text="""Since then the object of the present treatise is not mere speculation, as it is of some others (for we are inquiring not merely that we may know what virtue is but that we may become virtuous, else it would have been useless), we must consider as to the particular actions how we are to do them, because, as we have just said, the quality of the habits that shall be formed depends on these.""",
        quote_id=3,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        id=14,
        text="""Since the branch of philosophy on which we are at present engaged is not, like the others, theoretical in its aim -- because we are studying not to know what goodness is, but how to become good men, since otherwise it would be useless -- we must apply our minds to the problem of how our actions should be performed, because, as we have just said, it is these that actually determine our dispositions.""",
        quote_id=3,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        id=15,
        text="""Now, since the present subject is taken up, not for the sake of contemplation, as others are -- for we are conducting an examination, not so that we may know what virtue is, but so that we may become good, since otherwise there would be no benefit from it -- it is necessary to examine matters pertaining to actions, that is, how one ought to perform them.""",
        quote_id=3,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        id=16,
        text="""Let us resume our inquiry and state, in view of the fact that all knowledge and every pursuit aims at some good, what it is that we say political science aims at and what is the highest of all goods achievable by action.""",
        quote_id=4,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        id=17,
        text="""And now, resuming the statement with which we commenced, since all knowledge and moral choice grasps at good of some kind or another, what good is that which we say πολιτικὴ aims at? or, in other words, what is the highest of all the goods which are the objects of action?""",
        quote_id=4,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        id=18,
        text="""To resume. Since all knowledge and every pursuit aim at some good, what do we take to be the end of political science -- what is the highest of all practical goods?""",
        quote_id=4,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        id=19,
        text="""Now, let us pick up again and -- since all knowledge and every choice have some good as the object of their longing -- let us state what it is that we say to political art aims at and what the highest of all the goods related to action is.""",
        quote_id=4,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""Virtue, then, is a state of character concerned with choice, lying in a mean, i.e. the mean relative to us, this being determined by a rational principle, and by that principle by which the man of practical wisdom would determine it.""",
        quote_id=5,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""Virtue then is “a state apt to exercise deliberate choice, being in the relative mean, determined by reason, and as the man of practical wisdom would determine.”""",
        quote_id=5,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""So virtue is a purposive disposition, lying in a mean that is related to us and determined by a rational princple, and by that which a prudent man would use to deteremine it.""",
        quote_id=5,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""Virtue, therefore, is a characteristic marked by choice, residing in the mean relative to us, a characteristic defined by reason and as the prudent person would define it.""",
        quote_id=5,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""We must, however, not only make this general statement, but also apply it to the individual facts. For among statements about conduct those which are general apply more widely, but those which are particular are more genuine, since conduct has to do with individual cases, and our statements must harmonize with the facts in these cases.""",
        quote_id=6,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""It is not enough, however, to state this in general terms, we must also apply it to particular instances, because in treatises on moral conduct general statements have an air of vagueness, but those which go into detail one of greater reality: for the actions after all must be in detail, and the general statements, to be worth anything, must hold good here.""",
        quote_id=6,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""But a generalization of this kind is not enough; we must apply it to particular cases. When we are discussing actions, although general statements have a wider application, particular statements are closer to the truth. This is because actions are concerned with particular facts, and theories must be brought into harmony with these.""",
        quote_id=6,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""One must not only state this [definition] in general terms but also make it harmonize with the particulars involved. For in the case of arguments concerning actions, the general arguments are of wider application, whereas those pertaining to a part are truer: actions concern particulars and it is with these that the arguments ought to accord.""",
        quote_id=6,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""And first let us speak of courage. That it is a mean with regard to feelings of fear and confidence has already been made evident; and plainly the things we fear are terrible things, and these are, to speak without qualification, evils; for which reason people even define fear as expectation of evil. Now we fear all evils, e.g. disgrace, poverty, disease, friendlessness, death, but the brave man is not thought to be concerned with all; for to fear some things is even right and noble, and it is base not to fear them- e.g. disgrace; he who fears this is good and modest, and he who does not is shameless.""",
        quote_id=7,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""First, then, of Courage. Now that it is a mean state, in respect of fear and boldness, has been already said: further, the objects of our fears are obviously things fearful or, in a general way of statement, evils; which accounts for the common definition of fear, viz. “expectation of evil.” Of course we fear evils of all kinds: disgrace, for instance, poverty, disease, desolateness, death; but not all these seem to be the object-matter of the Brave man, because there are things which to fear is right and noble, and not to fear is base; disgrace, for example, since he who fears this is a good man and has a sense of honour, and he who does not fear it is shameless...""",
        quote_id=7,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""Let us begin with courage. It has already been shown that it is a mean state in relation to feelings of fear and confidence. Obviously the things that we fear are fearful, and such things are, broadly speaking, evils; which is why some people define fear as an expectation of evil. Well, we do fear all evils -- e.g. disgrace, poverty, sickness, friendlessness, death -- but not all of these are considered to be concerns of the courageous man, because there are some of them that it is right and honourable to fear, and shameful not to fear, e.g. disgrace.""",
        quote_id=7,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""And first let us speak about courage. Now, that it is a mean with respect to fear and confidence has already become apparent. It is clear that we fear frightening things, and these are, to speak unqualifiedly, bad things. Hence people also define fear as the anticipation of a bad thing. We fear, then, all the bad things -- for example, disrepute, poverty, sickness, friendlessness, and death -- but the courageous person is not held to be concerned witha ll of these. For some thigns one even out to fear, and it is noble to do so and shameful not to -- for example, disrepute, since he who fears this is decent and bashful, whereas he who does not is shameless...""",
        quote_id=7,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""After courage let us speak of temperance; for these seem to be the virtues of the irrational parts. We have said that temperance is a mean with regard to pleasures (for it is less, and not in the same way, concerned with pains); self-indulgence also is manifested in the same sphere. Now, therefore, let us determine with what sort of pleasures they are concerned.""",
        quote_id=8,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""Next let us speak of Perfected Self-Mastery, which seems to claim the next place to Courage, since these two are the Excellences of the Irrational part of the Soul. That it is a mean state, having for its object-matter Pleasures, we have already said (Pains being in fact its object-matter in a less degree and dissimilar manner), the state of utter absence of self-control has plainly the same object-matter; the next thing then is to determine what kind of Pleasures.""",
        quote_id=8,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""Next after courage let us say something about temperance, because these two virtues are considered to belong to the irrational parts of the soul. We have already said that temperance is a mean state with regard to pleasures (for it is less concerned with pains, and in a different way). Licentiousness is shown in the same field. So let us now determine what what kind of pleasures they are concerned.""",
        quote_id=8,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""After this virtue, let us speak about moderation, for these seem to be the virtues of the nonrational parts [of the soul]. Now, that moderation is a mean with respect to pleasures has been stated by us, for it is less concerned with pains than with pleasures, and it is concerned with each in dissimilar ways; licentiousness too is manifest in the same things. Let us now define the sorts of pleasures with which they are concerned.""",
        quote_id=8,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""Let us speak next of liberality. It seems to be the mean with regard to wealth; for the liberal man is praised not in respect of military matters, nor of those in respect of which the temrate man is praised, nor of judicial decisions, but with regard to the giving and taking of wealth, and especially in respect of giving. Now by 'wealth' we mean all the things whose value is measured by money.""",
        quote_id=9,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""We will next speak of Liberality. Now this is thought to be the mean state, having for its object-matter Wealth: I mean, the Liberal man is praised not in the circumstances of war, nor in those which constitute the character of perfected self-mastery, nor again in judicial decisions, but in respect of giving and receiving Wealth, chiefly the former. By the term Wealth I mean “all those things whose worth is measured by money.”""",
        quote_id=9,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""Let us speak about liberality. It seems to be the intermediate disposition with regard to money; because it is not in military affairs nor in the same sphere as temperance nor again in legal decisions that a person is praised as liberal, but with regard to the giving and receiving of money -- more particularly in the giving of it (by 'money' we mean everything of which the value is measured in terms of some currency).""",
        quote_id=9,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""Let us speak net in order about liberality. It seems, then, to be a mean with respect to money. For the liberal person is praised not in situations of war or in those in which the modreate person is praised, or, again, in those that involve legal adjudications. Rather, he is praised when it comes to the giving and taking of money, and more with regard to the giving of it. (We mean by money all those things whose worth is measured in legal currency.)""",
        quote_id=9,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""It would seem proper to discuss magnificence next. For this also seems to be a virtue concerned with wealth; but it does not like liberality extend to all the actions that are concerned with wealth, but only to those that involve expenditure; and in these it surpasses liberality in scale. For, as the name itself suggests, it is a fitting expenditure involving largeness of scale. But the scale is relative; for the expense of equipping a trireme is not the same as that of heading a sacred embassy. It is what is fitting, then, in relation to the agent, and to the circumstances and the object.""",
        quote_id=10,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""Next in order would seem to come a dissertation on Magnificence, this being thought to be, like liberality, a virtue having for its object-matter Wealth; but it does not, like that, extend to all transactions in respect of Wealth, but only applies to such as are expensive, and in these circumstances it exceeds liberality in respect of magnitude, because it is (what the very name in Greek hints at) fitting expense on a large scale: this term is of course relative: I mean, the expenditure of equipping and commanding a trireme is not the same as that of giving a public spectacle: “fitting” of course also is relative to the individual, and the matter wherein and upon which he has to spend.""",
        quote_id=10,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""Our next task it would seem, is to discuss magnificence, because this too is regarded as a virtue that has to do with money. But unlike liberality it does not extend to all financial transactions, but only to such as involve expenditure. In these it surpasses liberaility in scale, because (as its very name implies) it is befitting expenditure on a large scale. But the largeness is relative; for the outlay is not the same for the man who maintains a warship as it is for one who leads a delegation to a festival. So the suitability is relative to the agent himself, and to the circumstances and the object of his expenditure.""",
        quote_id=10,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""Going through what concerns magnificence as well would seem to follow next. For this too seems to be a certain virtue pertaining to money, although, unlike libarality, it does not extend to all actions involving money but concerns only expenditures; and in these expenditures, it surpasses liberality in greatness. For just as the name itself signifies, magnificence is a fitting expenditure on a great thing. But greatness is relative, since the expenditure is not the same for someone who outfits a trireme as for the sponsor of a sacred embassy. What is fitting, then, is relative to the person invovled and to the thing on which as well as that for which he makes the expenditure.""",
        quote_id=10,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""Pride seems even from its name to be concerned with great things; what sort of great things, is the first question we must try to answer. It makes no difference whether we consider the state of character or the man characterized by it. Now the man is thought to be proud who thinks himself worthy of great things, being worthy of them; for he who does so beyond his deserts is a fool, but no virtuous man is foolish or silly. The proud man, then, is the man we have described.""",
        quote_id=11,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""The very name of Great-mindedness implies, that great things are its object-matter; and we will first settle what kind of things. It makes no difference, of course, whether we regard the moral state in the abstract or as exemplified in an individual. Well then, he is thought to be Great-minded who values himself highly and at the same time justly, because he that does so without grounds is foolish, and no virtuous character is foolish or senseless. Well, the character I have described is Great-minded.""",
        quote_id=11,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""Greatness of soul, as the very name suggests, is concerned with things that are great, and we must first grasp of what sort these are. It makes no difference whether we consider the disposition or the person who corresponds to it. Well, a person is considered to be magnanimous if he thinks he is worth of great things, provided that he is worthy of them; because anyone who esteems his own worth unduly is foolish, and nobody who acts virtuously is foolish or stupid. The magnanimous man, then, is as we have described him.""",
        quote_id=11,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""Greatness of soul seems, even from its name, to be concerned with great things, and let us first grasp what sort of great things it concerns. It makes no difference whether we examine the characterstic or the person who accords with the characterstic. He, then, who deems himself worthy of great things and is worthy of them is held to be great souled. For he who does this in a manner contrary to his real worth is foolish, and no one who acts virtuously is foolish or mindless. The person spoken of, then, is great souled.""",
        quote_id=11,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""There seems to be in the sphere of honour also, as was said in our first remarks on the subject, a virtue which would appear to be related to pride as liberality is to magnificence. For neither of these has anything to do with the grand scale, but both dispose us as is right with regard to middling and unimportant objects; as in getting and giving of wealth there is a mean and an excess and defect, so too honour may be desired more than is right, or less, or from the right sources and in the right way.""",
        quote_id=12,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""... there seems to be a virtue having Honour also for its object (as we stated in the former book), which may seem to bear to Great-mindedness the same relation that Liberality does to Magnificence: that is, both these virtues stand aloof from what is great but dispose us as we ought to be disposed towards moderate and small matters. Further: as in giving and receiving of wealth there is a mean state, an excess, and a defect, so likewise in grasping after Honour there is the more or less than is right, and also the doing so from right sources and in right manner.""",
        quote_id=12,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""It seems, however, that in the spehere of honour too there is a kind of virtue, as we said at the beginning, which may be regarded as related to magnanimity in much the same way as liberality is to magnificence. For both these states are unconcerned with greatness, but dispose us in the right way towards matters of moderate or little importance. Just as in the receiving and giving of money there is a mean and an excess and a deficiency, so also in the desire for honour there are degrees of too much and too little, and a right source and a right manner.""",
        quote_id=12,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""But there seems to be a certain virtue also concerned with honor, just as was said in the first discussions, which would seem to stand in a similar way to greatness of soul as liberality stands to magnificence: both are at a remove from what is great but dispose us to be such as we ought to be when it comes to measured and small things. Just as there is a mean, an excess, and a deficiency in the taking and giving of money, so also in the longing for honor one can have more or less of such a longing than one ougth, and one can seek honor from where and in the way one ought.""",
        quote_id=12,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""Good temper is a mean with respect to anger; the middle state being unnamed, and the extremes almost without a name as well, we place good temper in the middle position, though it inclines towards the deficiency, which is without a name.""",
        quote_id=13,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""Meekness is a mean state, having for its object-matter Anger: and as the character in the mean has no name, and we may almost say the same of the extremes, we give the name of Meekness (leaning rather to the defect, which has no name either) to the character in the mean.""",
        quote_id=13,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""Patience is an intermediate state with regard to anger. The mean is really nameless, and the extremes nearly so; but we apply the name patience to the mean, although it tends towards describing the deficiency, which also lacks a name.""",
        quote_id=13,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""Gentleness is a mean with respect to anger. Since the middle term is nameless, as the extremes also pretty much are, we confer the name "gentleness" on the middle term, since it inclines in the direction of the deficiency, which is nameless.""",
        quote_id=13,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""In gatherings of men, in social life and the interchange of words and deeds, some men are thought to be obsequious, viz. those who to give pleasure praise everything and never oppose, but think it their duty 'to give no pain to the people they meet'; while those who, on the contrary, oppose everything and care not a whit about giving pain are called churlish and contentious. That the states we have named are culpable is plain enough, and that the middle state is laudable- that in virtue of which a man will put up with, and will resent, the right things and in the right way; but no name has been assigned to it, though it most resembles friendship.""",
        quote_id=14,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""Next, as regards social intercourse and interchange of words and acts, some men are thought to be Over-Complaisant who, with a view solely to giving pleasure, agree to everything and never oppose, but think their line is to give no pain to those they are thrown amongst: they, on the other hand, are called Cross and Contentious who take exactly the contrary line to these, and oppose in everything, and have no care at all whether they give pain or not. Now it is quite clear of course, that the states I have named are blameable, and that the mean between them is praiseworthy, in virtue of which a man will let pass what he ought as he ought, and also will object in like manner. However, this state has no name appropriated, but it is most like Friendship...""",
        quote_id=14,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""In contacts with other people, that is, in daily life and in discussions and dealings with others, some people are considered to be obsequious: to make themselves pleasant they praise everything and offer no resistance, thinking that they must avoid causing annoyance to the people that they meet. Those who take the opposite line to these, offering resistance to everything and not worrying at all about causing annoyance, are called surly or quarrelsome. It is not difficult to see that the said dispositions are culpable, and that the one that is intermediate between them, which will enable one to accept (and similarly to reject) the right thing in the right way, is praiseworthy. It has no definite name assigned to it, but what it most closely resembles is friendliness...""",
        quote_id=14,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""In our associations with one another, both in living together and in sharing in speeches and actions, some people are held to be obsequious: those who praise everyone with a view to pleasing them and oppose nothing, but rather suppose they ought not to cuase pain to anyone they may meet. At the opposite extreme to them are those people who oppose everything and give no thought whatever to causing others pain, people who are called surly and quarrelsome. It is not unclear, then, that the characteristics spoken of are blameworthy and that the middle term with respect to these -- in accord with which a person will approve of what he ought and in the way he ought, and similarly also disapprove -- is praiseworthy. But a specific name has not been given to this characteristic, though it seems most like friendship [or friendliness].""",
        quote_id=14,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""The mean opposed to boastfulness is found in almost the same sphere; and this also is without a name... let us now describe those who pursue truth or falsehood alike in words and deeds and in the claims they put forward. The boastful man, then, is thought to be apt to claim the things that bring glory, when he has not got them, or to claim more of them than he has, and the mock-modest man on the other hand to disclaim what he has or belittle it, while the man who observes the mean is one who calls a thing by its own name, being truthful both in life and in word, owning to what he has, and neither more nor less.""",
        quote_id=15,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""The mean state which steers clear of Exaggeration has pretty much the same object-matter as the last we described, and likewise has no name appropriated to it... we will now go on to speak of those who are True or False, alike in their words and deeds and in the claims which they advance. Now the Exaggerator is thought to have a tendency to lay claim to things reflecting credit on him, both when they do not belong to him at all and also in greater degree than that in which they really do: whereas the Reserved man, on the contrary, denies those which really belong to him or else depreciates them, while the mean character being a Plain-matter-of-fact person is Truthful in life and word, admitting the existence of what does really belong to him and making it neither greater nor less than the truth.""",
        quote_id=15,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""The same field of action, roughly speaking, belongs to the disposition intermediate between boasting and understatement... Let us now deal similarly with those who exhibit truth and falsehood in their speech and actions, i.e. in their pretensions. Well, the boaster is regarded as one who pretends to have distinguished qualities which he possesses either not at all or to a lesser degree than he pretends. The ironical man conversely is thought to disclaim qualities that he does possess, or to depreciate them; while the one who is intermediate between these two is a sort of individualist, sincere both in his daily life and in his speech, acknowledging the qualities that he possesses and neither exaggerating nor depreciating them.""",
        quote_id=15,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""Concerning pretty much the same things, there is also the mean related to boasting, but it too is nameless... Let us speak similarly also about those who tell the truth as well as those who state falsehoods related to speeches and actions, that is, in relation to what it is they pretend to. The boaster, then, seems apt to pretend to qualities held in high repute, both qualities he does not actually possess and those that are greater than the ones he does possess, whereas the ironist, conversely, seems to deny the qualities he actually possesses or to make them less; and the person in the middle between them is a kind of "plain dealer," since he is given to truthfulness, both in his life and his speech, acknowledging that the qualities he possesses are his own and neither exaggerating nor diminishing them.""",
        quote_id=15,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""Since life includes rest as well as activity, and in this is included leisure and amusement, there seems here also to be a kind of intercourse which is tasteful; there is such a thing as saying- and again listening to- what one should and as one should. The kind of people one is speaking or listening to will also make a difference. Evidently here also there is both an excess and a deficiency as compared with the mean.""",
        quote_id=16,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""Next, as life has its pauses and in them admits of pastime combined with Jocularity, it is thought that in this respect also there is a kind of fitting intercourse, and that rules may be prescribed as to the kind of things one should say and the manner of saying them; and in respect of hearing likewise (and there will be a difference between the saying and hearing such and such things). It is plain that in regard to these things also there will be an excess and defect and a mean.""",
        quote_id=16,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""Since one part of life is relaxation, and one aspect of this is entertaining conversation, it is considered that here too there is a kind of social conduct that is in good taste: that there are things that it is right to say, and a right way of saying them; and similarly with listening. And it will be an advantage if those in whose presence we talk and to whom we listen accept such standards. Clearly in this field too it is possible to exceed or fall short of the mean.""",
        quote_id=16,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""But since rest [or relaxation] too is a part of life, and a part of rest involves passing the time with playful amusement, it seems that here too there there is a certain suitable manner of association, that is, both certain things one ought to say to others and a certain manner of doing so, and similarly also with listening to others. It will also make a difference what sorts of people one speaks among and to what sorts one listens. It is clear that, regarding these matters as well, there is an excess and a deficiency with respect to a middle term.""",
        quote_id=16,
        vector=None,
        language="en",
        book_id=3,
    ),
    dict(
        text="""Shame should not be described as a virtue; for it is more like a feeling than a state of character. It is defined, at any rate, as a kind of fear of dishonour, and produces an effect similar to that produced by fear of danger; for people who feel disgraced blush, and those who fear death turn pale. Both, therefore, seem to be in a sense bodily conditions, which is thought to be characteristic of feeling rather than of a state of character.""",
        quote_id=17,
        vector=None,
        language="en",
        book_id=0,
    ),
    dict(
        text="""To speak of Shame as a Virtue is incorrect, because it is much more like a feeling than a moral state. It is defined, we know, to be “a kind of fear of disgrace,” and its effects are similar to those of the fear of danger, for they who feel Shame grow red and they who fear death turn pale. So both are evidently in a way physical, which is thought to be a mark of a feeling rather than a moral state.""",
        quote_id=17,
        vector=None,
        language="en",
        book_id=1,
    ),
    dict(
        text="""It is not correct to speak of modesty as a kind of virtue, because it is more like a feeling than a state. It is defined, at any rate, as a sort of fear of disrepute, and it has an effect very like that produced by the fear of danger; modesty makes people blush, and the fear of death turns them pale. So both appear to be in some sense corporeal, and this is thought to be more the mark of a feeling than of a state.""",
        quote_id=17,
        vector=None,
        language="en",
        book_id=2,
    ),
    dict(
        text="""It is not fitting to speak about a sense of shame as a particular vitue, for it seems more like a passion than a characteristic. It is defined, at any rate, as a certain fear of disrepute, and it turns out to resemble the fear of terrible things, for those who feel shame blush and those who fear death turn pale. Both, then, appear in some way to be bodily, which seems to be more a mark of a passion than of a characteristic.""",
        quote_id=17,
        vector=None,
        language="en",
        book_id=3,
    ),
    # dict(
    #     text="""""",
    #     vector=None,
    #     language="en",
    #     book_id=0,
    # ),
    # dict(
    #     text="""""",
    #     vector=None,
    #     language="en",
    #     book_id=1,
    # ),
    # dict(
    #     text="""""",
    #     vector=None,
    #     language="en",
    #     book_id=2,
    # ),
    # dict(
    #     text="""""",
    #     vector=None,
    #     language="en",
    #     book_id=3,
    # ),
)


virtues = [
    "courage",
    "temperance",
    "generosity",
    "good-temperedness",
    "proper pride",
    "friendliness",
    "good-humoredness",
    "modesty",
]


vices = [
    "cowardice",
    "rashness",
    "abstinence",
    "overindulgence",
    "stinginess",
    "wastefulness",
    "poor self-esteem",
    "arrogance",
    "apathy",
    "irascibility",
    "quarrelsomeness",
    "obsequiousness",
    "flattery",
    "boorishness",
    "buffonery",
    "shyness",
    "shamelessness",
]
